import './js/pageSwitcher';
import './js/mobileMenu';
import './js/modal';
import './js/modalRating';
import './js/exercises';
import './js/quote';
import './js/your-choice';
import './js/footer';
import './js/loader';
import './js/search/search-input';
// import './js/showPageError';
import './js/handlerScrollUp';
import './js/search/index';
